FROM node:20-alpine AS base

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/worker/package.json apps/worker/
COPY packages/db/package.json packages/db/

RUN npm ci --omit=dev

COPY packages/db ./packages/db
RUN npx prisma generate --schema packages/db/prisma/schema.prisma

COPY apps/worker ./apps/worker

ENV NODE_ENV=production

CMD ["node", "-r", "ts-node/register", "apps/worker/src/index.ts"]
